### ISSUE TITLE
Find list of words we don't want to use

### ISSUE THREAD

**Issue by Anguswaffle** [The-ABC-Crew/Quote-pics#13]
Stuff like conjunctions and other unusable words

**Comment by AJones1200** [comment]
Words to put in array to avoid: 
and
the
I 
you
we
they
them
at
is
not
of 
to
from
for
how
why
where
when
it
it's

**Comment by AJones1200** [comment]
he
she
a
you're
your
too
there
their
they're
with
in
do 
done
did
our
are
about
that
that's
who 
whose
mine 
yours
by

**Comment by AJones1200** [comment]
one
yes
no
ok
shit
bitch
fuck
ass
whore
slut
asshole
bastard
god
goddamn
goddammit
penis
vagina
pussy
dick
motherfucker
fucker
retard
retarded
fag 
faggot
dyke
libtard
shitty
piss
balls
bullshit
cock
cunt
tits
nuts
cocksucker

**Comment by AJones1200** [comment]
as
about

**Comment by AJones1200** [comment]
Done 11/6
