### ISSUE TITLE
Text placement

### ISSUE THREAD

**Issue by Anguswaffle** [The-ABC-Crew/Quote-pics#16]
Additional questions:

Is the text going to be in the same place for every image? (ie, centered)
Will it be placed in a random location every time?
Different fonts used?
Font sizing?

**Comment by AJones1200** [comment]
I think same place positioning should be used for the quote pic, but for the text, I'm not sure. Center would be more consistent, but making it random might be more interesting. I think we should use the same font on all quote pics, something bold that will show up on any pic, light or dark. Possibly white with black outline or vice versa. Font should be big enough that we can see it but fit into the quote pic regardless of the length of the quote, possibly using fitText in jQuery:                                https://css-tricks.com/fitting-text-to-a-container/
